### ISSUE TITLE
Check if CSS style exists independent of HTML elements

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/judge-html#165]
Sometimes it's easier/desirable to check something independent of HTML tags.

e.g.
```css
#yellow:hover {
    background-color: rgb(255, 210, 0);
}
```
