### ISSUE TITLE
Reset CSS for student submission render

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/judge-html#190]
The difference between the render with clean CSS and the render on Dodona isn't beneficial for the students. If the render is not reliable, a separate editor is required and it is less user-friendly.

Rowspan isn't visible in this example.
![table_5](https://user-images.githubusercontent.com/56451049/140722845-733535a8-2497-40d3-8b2d-76d8dd440d08.png)
![fullname](https://user-images.githubusercontent.com/56451049/140722930-e71eeda8-102e-463d-ad21-2c206837f9b7.png)

The Dodona doesn't support iframes in the student submission render.

@bmesuere suggests these options:

```css
#tag { all: initial; }

#tag * { all: unset; }  /* or */

#tag * { all: revert; }
```

Docs: 
- https://developer.mozilla.org/en-US/docs/Web/CSS/all
